export type AuthUser = {
	id : number
	uuid : string
	real_name : string | null
	nick_name : string | null
	phone : string
	avatar : string | null
	gender : number
	email ?: string | null
	status : number
	created_at : string
	updated_at : string
}

export type LoginResult = {
	token_type : string
	access_token : string
	user : AuthUser
}

export type SmsCodeResult = {
	message : string
	expires_in : number
}

export type UpdateProfilePayload = {
	real_name : string | null
	nick_name : string | null
	avatar : string | null
	gender : number
	email : string | null
}

export type UpdateUserResult = { message : string, user : AuthUser }
