export type ImProtocol = {
	auth_event : string
	join_event : string
	heartbeat_event : string
	heartbeat_interval : number
	send_event ?: string
}

export type ImConfig = {
	enabled : boolean
	user_id : string
	external_user_id : string | null
	token : string | null
	expires_in : number | null
	ws_url : string
	protocol : ImProtocol | null
	send_event ?: string
	retryable ?: boolean
}

export type ImConversationInfo = {
	conversation_no : string
	key : string
	type : string
	course_id : number
	class_id : number
	title : string
	id ?: any
	conversation_id ?: any
}

export type ImChatroomResult = {
	enabled : boolean
	user_id : string
	external_user_id : string | null
	token : string | null
	expires_in : number | null
	ws_url : string
	protocol : ImProtocol | null
	conversation_id ?: any
	send_event ?: string
	conversation : ImConversationInfo
	messages ?: UTSJSONObject[]
}

export type ImEnterResult = {
	conversation_no : string
	title : string
}

export type ChatMessage = {
	id : string
	conversation_no : string
	content : string
	user_id : string
	user_name : string
	created_at : string
	client_msg_id : string
}
