import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const envPath = resolve(rootDir, '.env')
const targetPath = resolve(rootDir, 'config/env.uts')

function parseEnv(content) {
  const values = new Map()
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (line === '' || line.startsWith('#')) continue
    const separator = line.indexOf('=')
    if (separator < 0) continue
    const key = line.slice(0, separator).trim()
    let value = line.slice(separator + 1).trim()
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1)
    }
    values.set(key, value)
  }
  return values
}

function envText(values, key, fallback = '') {
  const value = values.get(key)
  return value == null || value === '' ? fallback : value
}

function envNumber(values, key, fallback) {
  const value = Number.parseInt(envText(values, key, `${fallback}`), 10)
  return Number.isFinite(value) ? value : fallback
}

function utsString(value) {
  return JSON.stringify(value)
}

const values = parseEnv(readFileSync(envPath, 'utf8'))
const output = `// This file is generated from .env by scripts/sync-env.mjs.
// Do not edit this file directly; update .env and rerun the sync script.

export const APP_NAME = ${utsString(envText(values, 'APP_NAME', ''))}
export const API_BASE_URL = ${utsString(envText(values, 'API_BASE_URL', ''))}
export const IM_BASE_URL = ${utsString(envText(values, 'IM_BASE_URL', ''))}
export const VERSION_CHECK_PATH = ${utsString(envText(values, 'VERSION_CHECK_PATH', ''))}
export const REQUEST_TIMEOUT = ${envNumber(values, 'REQUEST_TIMEOUT', 15000)}
`

writeFileSync(targetPath, output, 'utf8')
